// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ9H-ywhrBUBnMilmqkO3vdrEnhqM6PGo',
    appId: '1:402243348220:web:92468315a9d6bdda529979',
    messagingSenderId: '402243348220',
    projectId: 'kaizaapp-95c80',
    authDomain: 'kaizaapp-95c80.firebaseapp.com',
    storageBucket: 'kaizaapp-95c80.appspot.com',
    measurementId: 'G-WWC15YNXC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbYuh0h8smdS8rhLRzH3D3Br0wJAkx7oM',
    appId: '1:402243348220:android:2b2669d94da7c242529979',
    messagingSenderId: '402243348220',
    projectId: 'kaizaapp-95c80',
    storageBucket: 'kaizaapp-95c80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEmy3opWVRMPa1FP4PL51yAjRWgS6UcE0',
    appId: '1:402243348220:ios:53644ce59d9eb7d2529979',
    messagingSenderId: '402243348220',
    projectId: 'kaizaapp-95c80',
    storageBucket: 'kaizaapp-95c80.appspot.com',
    iosBundleId: 'com.example.flatheadCountyCommunityEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEmy3opWVRMPa1FP4PL51yAjRWgS6UcE0',
    appId: '1:402243348220:ios:3015275974aefe8e529979',
    messagingSenderId: '402243348220',
    projectId: 'kaizaapp-95c80',
    storageBucket: 'kaizaapp-95c80.appspot.com',
    iosBundleId: 'com.example.flatheadCountyCommunityEvents.RunnerTests',
  );
}
