import 'package:flutter/material.dart';

// this class mostly generated by Google BARD!
class UserCircleIcon extends StatelessWidget {
  final String userName;
  final Color backgroundColor;
  final Color textColor;
  final double size;

  const UserCircleIcon({
    super.key,
    required this.userName,
    this.backgroundColor = Colors.blue,
    this.textColor = Colors.white,
    this.size = 40.0,
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        Container(
          width: size,
          height: size,
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            color: backgroundColor,
            //borderRadius: BorderRadius.circular(10),
            boxShadow: [
              BoxShadow(
                color: Colors.grey.withOpacity(0.5),
                spreadRadius: 5,
                blurRadius: 7,
                offset: Offset(0, 3),
              ),
            ],
          ),
          child: Center(
            child: Text(
              userName.toUpperCase(),
              style: TextStyle(
                color: textColor,
                fontSize: size * 0.6,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
        ),
      ],
    );
  }
}
